### ISSUE TITLE
Image size increased from 1.9 GB to over 3 GB

### ISSUE THREAD

**Issue by credmp** [thomasWeise/docker-pandoc#3]
I saw in your commit history that you are trying to reduced the image size, which is awesome. I noticed however that it jumped from 1.9GB to over 3 GB.

Any ideas on fixing this? I would like to help as I am using your image as a base for my own.

**Comment by credmp** [comment]
correction, it is 7.1GB now.
```
thomasweise/docker-pandoc           latest              9175b202ea8b        4 hours ago         7.1GB
```

**Comment by thomasWeise** [comment]
Hi.

Indeed.

I noticed that my "docker-texlive-full" did actually not provide a full TexLive installation.
TexLive, in its full version, installs a lot of documentation (like, 600 MB).
Originally, I uninstalled these packages afterwards.
If I understand correctly, this will automatically remove other packages, making the image relatively small.
Now I thought about emulating TexLive full by installing its sub-packages separately, but via some of the new commands, prohibit any documentation from being installed.
Unfortunately, this makes the image much bigger...

...so right now I am thinking about how to make it smaller again.
I guess in the end, I will have to drop some stuff.

Good candidates are fonts, which take up a lot of size.
However, there I feel pain, because I want that the image can process PDF with many fonts.

So yesterday, I tried to tweak and fiddle around, but it is still far from the goal size.

Cheers,
   Thomas

**Comment by thomasWeise** [comment]
Of course, any suggestions are welcome.

**Comment by thomasWeise** [comment]
In order to fix this issue, my current idea is as follows:
- [thomasWeise/docker-texlive-full](http://github.com/thomasWeise/docker-texlive-full) should, as the name implies, offer a rather "full" TeXLive installation.
- [thomasWeise/docker-texlive-thin](http://github.com/thomasWeise/docker-texlive-thin) is a new image with a thinner, smaller installation, tailored as basis for [thomasWeise/docker-pandoc](http://github.com/thomasWeise/docker-pandoc)
- [thomasWeise/docker-pandoc](http://github.com/thomasWeise/docker-pandoc) will use this new image as basis

**Comment by thomasWeise** [comment]
So, I am now progressing towards a much smaller image for [docker-pandoc](http://github.com/thomasWeise/docker-pandoc). The underlying [docker-texlive-thin](http://github.com/thomasWeise/docker-texlive-thin) image has much fewer packages installed.
But I am not sure if we still have the full functionality.
@credmp Thus, I would be happy if everyone using it can test if everything is still working as wanted.
If some required package is missing, I will add it to [docker-texlive-thin](http://github.com/thomasWeise/docker-texlive-thin).
Actually, I even got [docker-texlive-full](http://github.com/thomasWeise/docker-texlive-full) down to 1.5 GiB, too, so I may even switch back to using it as base package if necessary.

**Comment by credmp** [comment]
Nice, the size decreased significantly. There are some packages that are no longer available that I use (fontawesome and awesomebox being 2 of them). I will add these to my own image using `tlmgr` as I think not everybody uses these. I am going to give the images a try next week and will let you know!

**Comment by credmp** [comment]
Had a quick chance to run some tests. I install several specific packages using `tlmgr` in my own package and it works like a charm!

**Comment by thomasWeise** [comment]
@credmp Great.
During the coming few days, I will still be working on these images for a bit.
I am still trying to make them a bit smaller by deleting (hopefully) unnecessary files.
Then I will also test my own [bookbuildeR](http://github.com/thomasWeise/bookbuildeR) pipeline and maybe add some files back in.
But if it works so far, I am quite happy.

**Comment by thomasWeise** [comment]
I am now more or less finished with designing the new images.
The [docker-texlive-thin](https://github.com/thomasWeise/docker-texlive-thin) has increased again a bit in size. However, it is still much smaller than [docker-texlive-full](https://github.com/thomasWeise/docker-texlive-full).
My own pipeline seems to work fine now.
If anyone else's has issues now, just let me know.

**Comment by peey** [comment]
It seems like pdf engines (pdflatex, xelatex) are missing from the latest build

**Comment by thomasWeise** [comment]
Somehow it did not find a package but since I somewhere had an `|| true` in the script, it still completed "successfully".
I now make sure that builds really fail if any installation step fails.
Oddly enough, it now works - with exactly the same packages.
Must have been some connectivity fluke or whatever.

**Comment by TheBoegl** [comment]
First of all: thank you for the provided image! Keep up the good work!

I'm missing the siunitx package on the latest version. Could you please add them?

**Comment by thomasWeise** [comment]
So, I have worked a bit on the image again.
I think I managed to include the `siunitx` package mentioned by @TheBoegl .
The packages required by @credmp in his commit [47b02fd881202783bda7564473c8973264c4c345](https://github.com/credmp/docker-pandoc/commit/47b02fd881202783bda7564473c8973264c4c345) should now also be installed by default.

From a technical side, I tried to avoid to go the `tlmgr init-usertree` route, as this would clash with any subsequent `tlmgr init-usertree` (and thus would stop @credmp 's build from working).
Thus, I did `tlmgr init-usertree`, install the packages, the crudely try to merge the user tree into the system tree and then delete the user tree.
This should permit subsequent `tlmgr init-usertree`s to work.
At the same time, it allows me to kick out the package `texlive-fonts-extra`, which saves a lot of space.

But the approach used by me is indeed very crude...
Hence, I would like to ask all of yours to double-check whether the image is still working for you.

If you require any additional LaTeX package, then let me know and I can install it into the image as well.
If you require lots of packages, then maybe switch over to `thomasweise/docker-texlive-full`, which installs everything available in the Ubuntu TeX Live packages..
