### ISSUE TITLE
Question about Time to build 

### ISSUE THREAD

**Issue by rddaz2013** [thomasWeise/docker-pandoc#4]
thanks for your effort.

 I ask me  ...the compiler needs 1-2 hours to generate the image of pandoc + latex
 Is this a common duration when generating pandoc from sources?

René

**Comment by thomasWeise** [comment]
Hi.
Sorry for my late reply.

Indeed, the pandoc container takes that long.
The reason is, as you correctly pointed out, that I build pandoc from sources.

The reason for this, in turn, is that I need to put in several pandoc filters.
These are installed via cabal.
If I remember correctly, this is the only approach that works consistently for all filters.

I do not like this solution either, because it bloats the image as I install cabal (and am not fully sure what of that I can remove after the compile)... ...but at least it works.
In the future, I will see whether I can make the image a bit slimmer by deleting stuff more aggressively, but that won't change the long build time.
Currently, there is nothing I can do about that.

If the build time is an issue for you, you could use the image from docker hub: https://hub.docker.com/repository/docker/thomasweise/docker-pandoc/

Again, sorry for the late response.
All the best,
   Thomas.

**Comment by rddaz2013** [comment]
No problem, it's just a question from me - thx for the answer.

I was just worried that something was going wrong. 
Do you know a way how the ghc compiler outputs a little more messages so that you know that it is still doing something.

René

**Comment by thomasWeise** [comment]
The long runtimes are indeed an annoying issue, but, at the current state, not possible to prevent.
I think you could try adding `--verbose=3` option to the `cabal install` command to get more updates about what is going on.

If something should fail (or fail in future), here are some issues I encountered:

Generally, we are here a bit in a dodgy situation even with the `cabal` builds.
Some of the filters seem to have version clashes of their dependencies or of their dependencies and whatever `cabal` chooses to install or can offer to install.
If something is going wrong on your end, i.e., if some build fails, then most this could be a reason.
Then, it is important to figure out in which order the filters should be built and sometimes, options like `--allow-newer=base` used to override the version requirements may be the solution.
This *might possibly* become a problem later in production, because some of the behavior of the dependencies might have changed from what the filter is expecting, but I did never encounter any issue (and I think for `base` there probably should not be such an issue).

One big problem with docker hub is that it puts memory constraints on the builds - and `ghc` is very memory-hungry.
This led to aborted builds without any log information displayed, which was like the worst case to figure out what went wrong.
Thus, the `--ghc-options='+RTS -M2G -RTS'`, which limits the memory consumption of `ghc` to two gigs.
If I set it to one gig, then `ghc` will fail because it needs more memory.

These are the main issues I have encountered that could occur if something does go wrong.
But for now, hopefully, things will work (for a while) - even though quite slowly.
