### ISSUE TITLE
latest points to year old image

### ISSUE THREAD

**Issue by giuliboy** [thomasWeise/docker-pandoc#5]
Hi Thomas
i just wasted an hour, puzzling on why my image (which uses yours as base) was not using the latest pandoc version.

Problem:
 :latest is pointing to an old image....

![grafik](https://user-images.githubusercontent.com/26054853/130631961-e869b90c-3f89-46ce-9dea-27f6994d218e.png)

**Comment by thomasWeise** [comment]
Oops.
Thanks for letting me know.
It should be fixed now.

I updated the image last week manually.
Before, I used the dockerhub automated builds, which automatically built stuff.
These are no longer available.
So it was the first time I did this via `docker-push`.
I somehow assumed that the latest tag would automatically update itself if I pushed a new tag.
It turns out that it does not do this.
It should be fixed now.
